# -*- coding: utf-8 -*-
"""게임_워드클라우드.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16hpKOGd7cY-yrijk0eJ5F49BP7vbpi5Q
"""

import sys

!sudo add-apt-repository ppa:saiarcot895/chromium-beta
!sudo apt remove chromium-browser
!sudo snap remove chromium
!sudo apt install chromium-browser

!pip3 install selenium
!apt-get update
!apt install chromium-chromedriver
!cp /usr/lib/chromium-browser/chromedriver /usr/bin

sys.path.insert(0,'/usr/lib/chromium-browser/chromedriver')

import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service

options = webdriver.ChromeOptions()
options.add_argument('--headless')
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')

def loadDriver():
  webdriver_service = Service('/usr/bin/chromedriver')
  driver = webdriver.Chrome(service = webdriver_service, options=options)
  return driver

lines = ""

def loadDescription(URL):
  driver.get(URL)
  time.sleep(2)
  driver.find_element(By.XPATH,"/html/body/div[3]/div[2]/div/div[1]/section[1]/div[1]/div[3]/div/div/ul/li[2]/a").click()
  time.sleep(1)
  text = driver.find_element(By.XPATH, "/html/body/div[3]/div[2]/div/div[1]/section[1]/div[2]/div[2]/div/div[2]/p").text
  return text

driver = loadDriver()
t = loadDescription("https://search.naver.com/search.naver?where=nexearch&sm=tab_etc&mra=bkJB&pkid=3001&os=29286919&qvt=0&query=%EB%8D%B0%EB%93%9C%20%EC%8A%A4%ED%8E%98%EC%9D%B4%EC%8A%A4%20%EC%A0%95%EB%B3%B4")
lines = lines + t
print(lines)

# Commented out IPython magic to ensure Python compatibility.
import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm

# %config InlineBackend.figure_format = 'retina'

!apt -qq -y install fonts-nanum

fontpath = '/usr/share/fonts/truetype/nanum/NanumBarunGothic.ttf'
font = fm.FontProperties(fname=fontpath, size=9)
plt.rc('font', family='NanumBarunGothic')

import requests
import pandas as pd
from wordcloud import WordCloud
import matplotlib.pyplot as plt

wordcloud=WordCloud(font_path=fontpath).generate(lines)

fig=plt.figure(figsize=(10,10))
plt.imshow(wordcloud,interpolation='bilinear')
plt.axis('off')
plt.show()

!pip install konlpy

from konlpy.tag import Okt
from collections import Counter

okt = Okt()
noun = okt.nouns(lines)
count = Counter(noun)

noun_list = count.most_common(20)
for v in noun_list:
  print(v)